ktor:
  application:
    modules:
      - com.proyecto.ApplicationKt.module
  deployment:
    sslPort: 8080
  security:
    ssl:
      keyStore: cert/server_keystore.p12
      keyAlias: serverKeyPair
      keyStorePassword: 1234567
      privateKeyPassword: 1234567
database:
  uri: "mongodb://mongoadmin:mongopass@localhost/proyecto?authSource=admin"
  database: "proyecto"