ktor:
  application:
    modules:
      - com.proyecto.ApplicationKt.module
  deployment:
#    sslPort: 8080
  port: 8080
  security:
    ssl:
      keyStore: cert/server_keystore.p12
      keyAlias: serverKeyPair
      keyStorePassword: 1234567
      privateKeyPassword: 1234567
jwt:
  audience: "gymkhana"
  realm: "gymkhana experience"
  secret: "3sta€sL@ContraS€ñaD3Pru€b@"
  issuer: "Daniel Carmona"
  expiration: "86400"